services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  
  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller
  lb:
    image: nginx:1.27.4
    ports:
      - "8949:80"
    depends_on:
      - api

  # lb:
  #   image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
  #   ports:
  #     - "8949:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   depends_on:
  #     - api
 
  api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    ports: 
      - "7942:80"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=127.0.0.1,localhost,172.17.0.1,172.18.0.4
      - VIRTUAL_PORT=80
    volumes:
      - ./main.py:/code/main.py
    deploy:
     resources:
          limits:
            cpus: "2.0"
            memory: "400M"
  # cache:
  #   image: nginx
  #   ports:
  #     - "8043:80"
  #   volumes:
  #     - ./conf/cache/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - lb
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1.05"
  #         memory: "20M"
